name: wme-site
region: nyc
services:
  - name: wme
    build_command: npm install && npm run build
    run_command: npm start
    source_dir: /
    environment_slug: node-js
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /
    envs:
      - key: PORT
        value: "8080"
